language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.6-dev"
#  - "nightly"

sudo: false

# command to install dependencies
install:
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - nosetests --with-coverage --cover-package=acapi
  - flake8
# Disable sudo http://docs.travis-ci.com/user/migrating-from-legacy/
after_success:
  - coveralls
