language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

dist: xenial
sudo: required

install:
  - pip install -r requirements-dev.txt
script:
  - nosetests --with-coverage --cover-package=acapi
  - flake8
after_success:
  - coveralls
